<?php
/**
 * Songkick integration — widget helper functions.
 *
 * @package Santiago_Moraes
 */

defined( 'ABSPATH' ) || exit;

define( 'SM_SONGKICK_ARTIST_ID', '9999709' );
define( 'SM_SONGKICK_ARTIST_URL', 'https://www.songkick.com/artists/' . SM_SONGKICK_ARTIST_ID );
define( 'SM_SONGKICK_WIDGET_JS', 'https://widget-app.songkick.com/injector/' . SM_SONGKICK_ARTIST_ID );

/**
 * Render the Songkick Tourbox widget anchor tag.
 *
 * The injector script replaces this anchor with the full widget UI.
 * Data attributes match the code generated by Tourbox (tourbox.songkick.com/tools/widget).
 *
 * @param array $args {
 *     Optional. Override default data attributes.
 *
 *     @type string $theme               'dark' or 'light'. Default 'dark'.
 *     @type string $track_button        'on' or 'off'. Default 'off'.
 *     @type string $detect_style        'on' to inherit site fonts. Default 'on'.
 *     @type string $locale              Widget locale. Default 'es'.
 *     @type string $other_artists       Show other artists. Default 'on'.
 *     @type string $share_button        Show share button. Default 'on'.
 *     @type string $country_filter      Country filter. Default 'off'.
 *     @type string $rsvp                RSVP button. Default 'on'.
 *     @type string $request_show        Request a show. Default 'on'.
 *     @type string $past_events         Show past events. Default 'off'.
 *     @type string $past_events_offtour Past off-tour events. Default 'off'.
 *     @type string $remind_me           Remind me button. Default 'off'.
 * }
 */
function sm_songkick_widget( $args = array() ) {
	$defaults = array(
		'theme'               => 'dark',
		'track_button'        => 'off',
		'detect_style'        => 'on',
		'locale'              => 'es',
		'other_artists'       => 'on',
		'share_button'        => 'on',
		'country_filter'      => 'off',
		'rsvp'                => 'on',
		'request_show'        => 'on',
		'past_events'         => 'off',
		'past_events_offtour' => 'off',
		'remind_me'           => 'off',
	);
	$args = wp_parse_args( $args, $defaults );
	?>
	<a href="<?php echo esc_url( SM_SONGKICK_ARTIST_URL ); ?>"
	   class="songkick-widget"
	   data-theme="<?php echo esc_attr( $args['theme'] ); ?>"
	   data-track-button="<?php echo esc_attr( $args['track_button'] ); ?>"
	   data-detect-style="<?php echo esc_attr( $args['detect_style'] ); ?>"
	   data-locale="<?php echo esc_attr( $args['locale'] ); ?>"
	   data-other-artists="<?php echo esc_attr( $args['other_artists'] ); ?>"
	   data-share-button="<?php echo esc_attr( $args['share_button'] ); ?>"
	   data-country-filter="<?php echo esc_attr( $args['country_filter'] ); ?>"
	   data-rsvp="<?php echo esc_attr( $args['rsvp'] ); ?>"
	   data-request-show="<?php echo esc_attr( $args['request_show'] ); ?>"
	   data-past-events="<?php echo esc_attr( $args['past_events'] ); ?>"
	   data-past-events-offtour="<?php echo esc_attr( $args['past_events_offtour'] ); ?>"
	   data-remind-me="<?php echo esc_attr( $args['remind_me'] ); ?>"
	   style="display:none;"
	></a>
	<?php
}

/**
 * Enqueue the Songkick widget injector script on pages that need it.
 */
function sm_songkick_enqueue_widget() {
	if ( is_front_page() || is_page_template( 'templates/template-shows.php' ) ) {
		wp_enqueue_script(
			'songkick-widget',
			SM_SONGKICK_WIDGET_JS,
			array(),
			null,
			true
		);
	}
}
add_action( 'wp_enqueue_scripts', 'sm_songkick_enqueue_widget' );
